### ISSUE TITLE
Highlight all trailer names in a git commit message?

### ISSUE THREAD

**Issue by nogweii** [tpope/vim-git#76]
I would like all trailer names (like "Signed-off-by") to have a highlight group, so that I may apply a color to make them distinct. This is a more generic version of #69.

The best reference I've been able to find so far on their syntax is the [`git-interpret-trailers(1)`](https://git-scm.com/docs/git-interpret-trailers) man page. (Scanning through the git source, all of the parsing is handled in [`trailer.c`](https://github.com/git/git/blob/master/trailer.c) & `trailer.h`.)

The man page references [RFC 822](https://datatracker.ietf.org/doc/html/rfc822), and for ease here is the declared BNF for headers:

     header      =  field-name ":" [ field-body ] CRLF
     
     field-name  =  1*<any CHAR, excluding CTLs, SPACE, and ":">
     
     field-body  =  field-body-contents
                    [CRLF LWSP-char field-body]
     
     field-body-contents =
                   <the ASCII characters making up the field-body, as
                    defined in the following sections, and consisting
                    of combinations of atom, quoted-string, and
                    specials tokens, or else consisting of texts>

There is also the ability to fold a trailer's contents (in RFC 822's language, the "field body") over multiple lines, so long as the additional lines are prefixed with whitespace. Not sure how to represent that using vim's regex, or if that's something that can be skipped for now. I have yet to see any git commits with a multi-line trailer, but wanted to mention it.

**Comment by tpope** [comment]
Highlighting all trailers eliminates the problem that killed #69, trading it for the seemingly more tractable challenge of avoiding false positives. The manpage spells out how Git itself avoids false positives pretty explicitly:

> Existing trailers are extracted from the input message by looking for a group of one or more lines that (i) is all trailers, or (ii) contains at least one Git-generated or user-configured trailer and consists of at least 25% trailers. The group must be preceded by one or more empty (or whitespace-only) lines. The group must either be at the end of the message or be the last non-whitespace lines before a line that starts with `---` (followed by a space or the end of the line).

The (i) here is straightforward, while for (ii), "user-configured trailer" is difficult and "25%" is effectively impossible. But I think it's probably fine to ditch (ii), that seems to me to be more of a heuristic to recover a botched message than an officially sanctioned syntax. And the `---` doesn't apply here; instead, we need to be the last block of content of the file before the trailing comments and diff. In practice, I think "before a comment line" should be good enough, even if that allows a few false positives.

Prototyping this was easier than describing it, so have a look at the `trailers` branch. Like most highlights that use look-aheads/look-behinds, it's a bit on the fiddly side, but since trailers are generally generated rather than edited, that's probably fine.

@rohieb you might want to take a look at this too.

**Comment by nogweii** [comment]
Oh, wow, that was quick! I was thinking about taking a stab at it over the weekend, ha. Thanks for the quick response. :smile: 

Two thoughts:

* I was envisioning a much simpler regex to match the trailer name, something like `^[:alnum:-]+:` perhaps? (off the top of my head) Perhaps that is too naive, so the use of look-ahead is needed to mitigate the false positives, as you mentioned
* Editing has an interesting behavior, where the highlight doesn't seem to update all that quickly. I can type out `Foo-bar: blah` but it's not until I leave insert mode does the highlight get applied. Once, it even took a couple of seconds after leaving insert mode. I wonder if this is because of the look-ahead in the regex, or if it's something Neovim is doing. While a bit surprising, it's not an issue.

Nice work, thanks again for the super rapid turnaround! :+1:

**Comment by tpope** [comment]
> Oh, wow, that was quick! I was thinking about taking a stab at it over the weekend, ha. Thanks for the quick response. 
> 
> Two thoughts:
> 
> * I was envisioning a much simpler regex to match the trailer name, something like `^[:alnum:-]+:` perhaps? (off the top of my head) Perhaps that is too naive, so the use of look-ahead is needed to mitigate the false positives, as you mentioned

The trailer itself is matched that way, with the addition of whitespace before the colon since the manpage says that's permitted.
The shenanigans are for defining the paragraph _containing_ the trailers.

The look-ahead is to confirm that the next line is a `#` comment without actually including the comment in the pattern. Similarly, there's a look-behind to confirm we're following a blank line without including it, but we could probably get away with including it if that made the pattern more stable.

> * Editing has an interesting behavior, where the highlight doesn't seem to update all that quickly. I can type out `Foo-bar: blah` but it's not until I leave insert mode does the highlight get applied. Once, it even took a couple of seconds after leaving insert mode. I wonder if this is because of the look-ahead in the regex, or if it's something Neovim is doing. While a bit surprising, it's not an issue.

You can test by stripping out the look-ahead and/or the look-behind and see if that improves things. Both of those can cause behaviors like you describe, but multi-line patterns in general can too. Vim would have to start over highlighting from the top after every keypress to 100% eliminate issues like this.

**Comment by rohieb** [comment]
Oh yes thank you, I like this approach! (And now I think that git-cherry-pick should conform to this logic too and add a RFC822-style trailer instead of `(cherry picked from commit …)` 🤔)

**Comment by tpope** [comment]
Yeah it's screaming for it, I can only assume upstream decided "if it ain't broke, don't fix it."

**Comment by tpope** [comment]
On a related note, I am pleased to report a trailer of the form `Resolves: https://github.com/tpope/vim-git/issues/76` does work to close the issue. I might start doing that from now on. :blush:

**Comment by jvortmann** [comment]
Hey @tpope you can also do something like:

```
    Github-issue: #7
    Github-action: fix #7
```

Where the later might be only on the last commit if more commits were related to an issue.
This makes the `git shortlog --group=trailer:github-issue` or `git shortlog --group=trailer:github-action` work as expected to list things by issue or action, and still closes|resolves|fix things on Github.
